### PR TITLE
Introduce SetMultiValidationFunc to validate struct using multiple fields

### PR DESCRIPTION
**Pull request by mash**
Please see https://github.com/mash/validator/commit/5d679c8a70c18ddaf63bdbf40ce2940d81dec114#diff-bf215ece4e5166da723b1e19a0d6b1cdR274
I'll add comments and write usage in readme if you like it.

### CODE REVIEW

**Comment by jameshartig** [comment]
I have found myself needing a struct-wide validation function at times but I don't like the "multi" nomenclature and it seems weird to put the tags still on the fields when they apply to the struct. @mash for now I think the way to do this would just be to manually call something like `mv.Valid(yourStructHere, "same")` after defining the validationFunc  for `same`

**Comment by mash** [comment]
Agree that it's weird, but I didn't like the manual approach as well.

Just got an idea, how about:
`validator.SetStructValidationFunc(RequestParams{}, IsValidRequestParams)`
using reflection?

**Comment by LihMeh** [comment]
That's exactly what I've been looking for!
Any changes for this MR to be be merged if I fix the conflicts?

**Comment by jameshartig** [comment]
@LihMeh you can add `validate` tags to fields that are structs and it will run the validation function on the struct itself. You can see an example in the tests: https://github.com/go-validator/validator/blob/v2/validator_test.go#L290

**Pull request closed without merging**
